# Generated by Django 4.1.3 on 2023-02-27 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('movies', '0004_movies_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='category_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
